import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#141721] min-h-screen flex flex-col`}>
        <div className="flex flex-col min-h-screen">
          <header>
            {/* Header-komponent */}
            <div className="sticky top-0 z-50">
              {/* @ts-ignore */}
              {require('./components/Header').default()}
            </div>
          </header>
          <main className="flex-1 container mx-auto px-4">
            {children}
          </main>
          <footer>
            {/* Footer-komponent */}
            <div>
              {/* @ts-ignore */}
              {require('./components/Footer').default()}
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
